//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokInterface.Properties {
    using System;

    /// <summary>rongly-typed resource class, for looking up localized strings, etc</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoktaiResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoktaiResources() { }

        /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BokInterface.Properties.Resources", typeof(BoktaiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sol_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("sol_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap luna_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("luna_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap flame_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("flame_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap frost_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("frost_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cloud_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("cloud_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earth_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("earth_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dark_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("dark_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap star_lens
        {
            get
            {
                object obj = ResourceManager.GetObject("star_lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fighter {
            get {
                object obj = ResourceManager.GetObject("fighter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap knight
        {
            get
            {
                object obj = ResourceManager.GetObject("knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap crusader
        {
            get
            {
                object obj = ResourceManager.GetObject("crusader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dragoon
        {
            get
            {
                object obj = ResourceManager.GetObject("dragoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fencer
        {
            get
            {
                object obj = ResourceManager.GetObject("fencer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap swordsman
        {
            get
            {
                object obj = ResourceManager.GetObject("swordsman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap swordmaster
        {
            get
            {
                object obj = ResourceManager.GetObject("swordmaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap samurai
        {
            get
            {
                object obj = ResourceManager.GetObject("samurai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap axel
        {
            get
            {
                object obj = ResourceManager.GetObject("axel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap vortex
        {
            get
            {
                object obj = ResourceManager.GetObject("vortex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tornado
        {
            get
            {
                object obj = ResourceManager.GetObject("tornado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tempest
        {
            get
            {
                object obj = ResourceManager.GetObject("tempest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap spear
        {
            get
            {
                object obj = ResourceManager.GetObject("spear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap lance
        {
            get
            {
                object obj = ResourceManager.GetObject("lance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap javelin
        {
            get
            {
                object obj = ResourceManager.GetObject("javelin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap phalanx
        {
            get
            {
                object obj = ResourceManager.GetObject("phalanx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap knife
        {
            get
            {
                object obj = ResourceManager.GetObject("knife", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dagger
        {
            get
            {
                object obj = ResourceManager.GetObject("dagger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap gradius
        {
            get
            {
                object obj = ResourceManager.GetObject("gradius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap calamity
        {
            get
            {
                object obj = ResourceManager.GetObject("calamity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap juggler
        {
            get
            {
                object obj = ResourceManager.GetObject("juggler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wizard
        {
            get
            {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap stalker
        {
            get
            {
                object obj = ResourceManager.GetObject("stalker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap beatmania
        {
            get
            {
                object obj = ResourceManager.GetObject("beatmania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap guardian
        {
            get
            {
                object obj = ResourceManager.GetObject("guardian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap phantom
        {
            get
            {
                object obj = ResourceManager.GetObject("phantom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap single_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("single_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap double_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("double_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap triple_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("triple_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap quad_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("quad_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap quint_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("quint_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap infinite_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("infinite_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chaos_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("chaos_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap astro_battery
        {
            get
            {
                object obj = ResourceManager.GetObject("astro_battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
