//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokInterface.Properties {
    using System;

    /// <summary>rongly-typed resource class, for looking up localized strings, etc</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DsResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DsResources() { }

        /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BokInterface.Properties.Resources", typeof(DsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rotten_fruit {
            get {
                object obj = ResourceManager.GetObject("rotten_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rotten_meat {
            get {
                object obj = ResourceManager.GetObject("rotten_meat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cure_drop {
            get {
                object obj = ResourceManager.GetObject("cure_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earth_fruit {
            get {
                object obj = ResourceManager.GetObject("earth_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap delicious_meat {
            get {
                object obj = ResourceManager.GetObject("delicious_meat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap healing_potion {
            get {
                object obj = ResourceManager.GetObject("healing_potion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cure_bulb {
            get {
                object obj = ResourceManager.GetObject("cure_bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dried_meat {
            get {
                object obj = ResourceManager.GetObject("dried_meat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap heaven_fruit {
            get {
                object obj = ResourceManager.GetObject("heaven_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap stagnant_water {
            get {
                object obj = ResourceManager.GetObject("stagnant_water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magic_drop {
            get {
                object obj = ResourceManager.GetObject("magic_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_fruit {
            get {
                object obj = ResourceManager.GetObject("solar_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magical_ice_pop {
            get {
                object obj = ResourceManager.GetObject("magical_ice_pop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magical_drink {
            get {
                object obj = ResourceManager.GetObject("magical_drink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magic_potion {
            get {
                object obj = ResourceManager.GetObject("magic_potion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magic_bulb {
            get {
                object obj = ResourceManager.GetObject("magic_bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap miracle_ice_pop {
            get {
                object obj = ResourceManager.GetObject("miracle_ice_pop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap midnight_sun_fruit {
            get {
                object obj = ResourceManager.GetObject("midnight_sun_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap melted_chocolate {
            get {
                object obj = ResourceManager.GetObject("melted_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate_gob {
            get {
                object obj = ResourceManager.GetObject("chocolate_gob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate {
            get {
                object obj = ResourceManager.GetObject("chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap milk_chocolate {
            get {
                object obj = ResourceManager.GetObject("milk_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap deluxe_chocolate {
            get {
                object obj = ResourceManager.GetObject("deluxe_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap restorative {
            get {
                object obj = ResourceManager.GetObject("restorative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wild_card {
            get {
                object obj = ResourceManager.GetObject("wild_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap resurrective {
            get {
                object obj = ResourceManager.GetObject("resurrective", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap moon_dew {
            get {
                object obj = ResourceManager.GetObject("moon_dew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap full_moon_dew {
            get {
                object obj = ResourceManager.GetObject("full_moon_dew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap protect_fruit {
            get {
                object obj = ResourceManager.GetObject("protect_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap spoiled_milk {
            get {
                object obj = ResourceManager.GetObject("spoiled_milk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap milk {
            get {
                object obj = ResourceManager.GetObject("milk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap yogurt {
            get {
                object obj = ResourceManager.GetObject("yogurt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fruit_yogurt {
            get {
                object obj = ResourceManager.GetObject("fruit_yogurt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap antidote {
            get {
                object obj = ResourceManager.GetObject("antidote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap elixir {
            get {
                object obj = ResourceManager.GetObject("elixir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap clairvoyance_fruit {
            get {
                object obj = ResourceManager.GetObject("clairvoyance_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap speed_fruit {
            get {
                object obj = ResourceManager.GetObject("speed_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap stealth_fruit {
            get {
                object obj = ResourceManager.GetObject("stealth_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap power_fruit {
            get {
                object obj = ResourceManager.GetObject("power_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate_banana {
            get {
                object obj = ResourceManager.GetObject("chocolate_banana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap endurance_fruit {
            get {
                object obj = ResourceManager.GetObject("endurance_fruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warrior_s_ethic {
            get {
                object obj = ResourceManager.GetObject("warrior_s_ethic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap loser_stick {
            get {
                object obj = ResourceManager.GetObject("loser_stick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap winner_stick {
            get {
                object obj = ResourceManager.GetObject("winner_stick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap topaz {
            get {
                object obj = ResourceManager.GetObject("topaz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap emerald {
            get {
                object obj = ResourceManager.GetObject("emerald", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap jasper {
            get {
                object obj = ResourceManager.GetObject("jasper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ruby {
            get {
                object obj = ResourceManager.GetObject("ruby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap gold_nugget {
            get {
                object obj = ResourceManager.GetObject("gold_nugget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garnet {
            get {
                object obj = ResourceManager.GetObject("garnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap swordsman_photo {
            get {
                object obj = ResourceManager.GetObject("swordsman_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap gunslinger_photo {
            get {
                object obj = ResourceManager.GetObject("gunslinger_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap duke_photo {
            get {
                object obj = ResourceManager.GetObject("duke_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap poster_girl_photo {
            get {
                object obj = ResourceManager.GetObject("poster_girl_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dark_card {
            get {
                object obj = ResourceManager.GetObject("dark_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earthly_robe {
            get {
                object obj = ResourceManager.GetObject("earthly_robe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap old_solar_gun {
            get {
                object obj = ResourceManager.GetObject("old_solar_gun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap broken_dark_gun {
            get {
                object obj = ResourceManager.GetObject("broken_dark_gun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap junk_part {
            get {
                object obj = ResourceManager.GetObject("junk_part", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sound_data {
            get {
                object obj = ResourceManager.GetObject("sound_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap flame {
            get {
                object obj = ResourceManager.GetObject("flame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap frost {
            get {
                object obj = ResourceManager.GetObject("frost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bomb {
            get {
                object obj = ResourceManager.GetObject("bomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap trap {
            get {
                object obj = ResourceManager.GetObject("trap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap biometricsw {
            get {
                object obj = ResourceManager.GetObject("biometricsw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap christmas_cake {
            get {
                object obj = ResourceManager.GetObject("christmas_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap new_year_s_money {
            get {
                object obj = ResourceManager.GetObject("new_year_s_money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap valentine_s_day_chocolate {
            get {
                object obj = ResourceManager.GetObject("valentine_s_day_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ryuusei {
            get {
                object obj = ResourceManager.GetObject("ryuusei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap mobile_unit {
            get {
                object obj = ResourceManager.GetObject("mobile_unit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_goggles {
            get {
                object obj = ResourceManager.GetObject("solar_goggles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap paper_bag {
            get {
                object obj = ResourceManager.GetObject("paper_bag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap letter_to_gatekeeper {
            get {
                object obj = ResourceManager.GetObject("letter_to_gatekeeper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_sensor_ver_1 {
            get {
                object obj = ResourceManager.GetObject("solar_sensor_ver_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_sensor_ver_2 {
            get {
                object obj = ResourceManager.GetObject("solar_sensor_ver_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_sensor_ver_3 {
            get {
                object obj = ResourceManager.GetObject("solar_sensor_ver_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap red_key {
            get {
                object obj = ResourceManager.GetObject("red_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap yellow_key {
            get {
                object obj = ResourceManager.GetObject("yellow_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap blue_key {
            get {
                object obj = ResourceManager.GetObject("blue_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap transer {
            get {
                object obj = ResourceManager.GetObject("transer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap visualizer {
            get {
                object obj = ResourceManager.GetObject("visualizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bouquet {
            get {
                object obj = ResourceManager.GetObject("bouquet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fresh_picked_herbs {
            get {
                object obj = ResourceManager.GetObject("fresh_picked_herbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap caravan_package_red {
            get {
                object obj = ResourceManager.GetObject("caravan_package_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap caravan_package_blue {
            get {
                object obj = ResourceManager.GetObject("caravan_package_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap caravan_package_yellow {
            get {
                object obj = ResourceManager.GetObject("caravan_package_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fresh_picked_mushrooms {
            get {
                object obj = ResourceManager.GetObject("fresh_picked_mushrooms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap spare_bottlecap {
            get {
                object obj = ResourceManager.GetObject("spare_bottlecap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap luna_emblem {
            get {
                object obj = ResourceManager.GetObject("luna_emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sol_emblem {
            get {
                object obj = ResourceManager.GetObject("sol_emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dark_emblem {
            get {
                object obj = ResourceManager.GetObject("dark_emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dark_eye {
            get {
                object obj = ResourceManager.GetObject("dark_eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap training_goggles {
            get {
                object obj = ResourceManager.GetObject("training_goggles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap muspell_headgear {
            get {
                object obj = ResourceManager.GetObject("muspell_headgear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap hresvelgr_headgear {
            get {
                object obj = ResourceManager.GetObject("hresvelgr_headgear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap nidhoggr_headgear {
            get {
                object obj = ResourceManager.GetObject("nidhoggr_headgear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garmr_headgear {
            get {
                object obj = ResourceManager.GetObject("garmr_headgear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap moonlight_beauty {
            get {
                object obj = ResourceManager.GetObject("moonlight_beauty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earth_amulet {
            get {
                object obj = ResourceManager.GetObject("earth_amulet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wind_amulet {
            get {
                object obj = ResourceManager.GetObject("wind_amulet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ice_flame_amulet {
            get {
                object obj = ResourceManager.GetObject("ice_flame_amulet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap burning_headband {
            get {
                object obj = ResourceManager.GetObject("burning_headband", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cool_bandanna {
            get {
                object obj = ResourceManager.GetObject("cool_bandanna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap eclipse_eye {
            get {
                object obj = ResourceManager.GetObject("eclipse_eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap eclipse_goggles {
            get {
                object obj = ResourceManager.GetObject("eclipse_goggles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cursed_mask {
            get {
                object obj = ResourceManager.GetObject("cursed_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warrior_s_mask {
            get {
                object obj = ResourceManager.GetObject("warrior_s_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap pegasusrockhead {
            get {
                object obj = ResourceManager.GetObject("pegasusrockhead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap leather_suit {
            get {
                object obj = ResourceManager.GetObject("leather_suit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap battle_suit {
            get {
                object obj = ResourceManager.GetObject("battle_suit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap muspell_arms {
            get {
                object obj = ResourceManager.GetObject("muspell_arms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap hresvelgr_arms {
            get {
                object obj = ResourceManager.GetObject("hresvelgr_arms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap nidhoggr_arms {
            get {
                object obj = ResourceManager.GetObject("nidhoggr_arms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garmr_arms {
            get {
                object obj = ResourceManager.GetObject("garmr_arms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ninja_suit {
            get {
                object obj = ResourceManager.GetObject("ninja_suit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap hot_space {
            get {
                object obj = ResourceManager.GetObject("hot_space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap winter_s_tale {
            get {
                object obj = ResourceManager.GetObject("winter_s_tale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wild_wind {
            get {
                object obj = ResourceManager.GetObject("wild_wind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap staying_power {
            get {
                object obj = ResourceManager.GetObject("staying_power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap green_leaf_cape {
            get {
                object obj = ResourceManager.GetObject("green_leaf_cape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap blood_sucker {
            get {
                object obj = ResourceManager.GetObject("blood_sucker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap soul_saver {
            get {
                object obj = ResourceManager.GetObject("soul_saver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cursed_scarf {
            get {
                object obj = ResourceManager.GetObject("cursed_scarf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warrior_s_scarf {
            get {
                object obj = ResourceManager.GetObject("warrior_s_scarf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dragonrockbody {
            get {
                object obj = ResourceManager.GetObject("dragonrockbody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap leather_boots {
            get {
                object obj = ResourceManager.GetObject("leather_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap battle_boots {
            get {
                object obj = ResourceManager.GetObject("battle_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap muspell_legs {
            get {
                object obj = ResourceManager.GetObject("muspell_legs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap hresvelgr_legs {
            get {
                object obj = ResourceManager.GetObject("hresvelgr_legs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap nidhoggr_legs {
            get {
                object obj = ResourceManager.GetObject("nidhoggr_legs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garmr_legs {
            get {
                object obj = ResourceManager.GetObject("garmr_legs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fire_starter {
            get {
                object obj = ResourceManager.GetObject("fire_starter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ice_breaker {
            get {
                object obj = ResourceManager.GetObject("ice_breaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sky_runner {
            get {
                object obj = ResourceManager.GetObject("sky_runner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap grass_dancer {
            get {
                object obj = ResourceManager.GetObject("grass_dancer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap day_walker {
            get {
                object obj = ResourceManager.GetObject("day_walker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap night_stalker {
            get {
                object obj = ResourceManager.GetObject("night_stalker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap training_boots {
            get {
                object obj = ResourceManager.GetObject("training_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bounty_boots {
            get {
                object obj = ResourceManager.GetObject("bounty_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cursed_boots {
            get {
                object obj = ResourceManager.GetObject("cursed_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warrior_s_boots {
            get {
                object obj = ResourceManager.GetObject("warrior_s_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap leorockleg {
            get {
                object obj = ResourceManager.GetObject("leorockleg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap silver_star {
            get {
                object obj = ResourceManager.GetObject("silver_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap red_cross {
            get {
                object obj = ResourceManager.GetObject("red_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap snake_eyes {
            get {
                object obj = ResourceManager.GetObject("snake_eyes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap blue_spine {
            get {
                object obj = ResourceManager.GetObject("blue_spine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
