//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokInterface.Properties {
    using System;

    /// <summary>rongly-typed resource class, for looking up localized strings, etc</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() { }

        /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BokInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap stairs1 {
            get {
                object obj = ResourceManager.GetObject("stairs1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap stairs2 {
            get {
                object obj = ResourceManager.GetObject("stairs2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap django1 {
            get {
                object obj = ResourceManager.GetObject("django1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap django2 {
            get {
                object obj = ResourceManager.GetObject("django2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap enemy {
            get {
                object obj = ResourceManager.GetObject("enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ice {
            get {
                object obj = ResourceManager.GetObject("ice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap lava {
            get {
                object obj = ResourceManager.GetObject("lava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_panel {
            get {
                object obj = ResourceManager.GetObject("solar_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap qmark {
            get {
                object obj = ResourceManager.GetObject("qmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Icon similar to (Icon).</summary>
        internal static System.Drawing.Icon lita {
            get {
                object obj = ResourceManager.GetObject("lita", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Icon similar to (Icon).</summary>
        internal static System.Drawing.Icon lucian {
            get {
                object obj = ResourceManager.GetObject("lucian", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Icon similar to (Icon).</summary>
        internal static System.Drawing.Icon nero {
            get {
                object obj = ResourceManager.GetObject("nero", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Icon similar to (Icon).</summary>
        internal static System.Drawing.Icon ringo {
            get {
                object obj = ResourceManager.GetObject("ringo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Icon similar to (Icon).</summary>
        internal static System.Drawing.Icon trinity {
            get {
                object obj = ResourceManager.GetObject("trinity", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
