//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokInterface.Properties {
    using System;
    
    /// <summary>rongly-typed resource class, for looking up localized strings, etc</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShinbokResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShinbokResources() { }
        
        /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BokInterface.Properties.Resources", typeof(ShinbokResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        
        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap healer {
            get {
                object obj = ResourceManager.GetObject("healer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earthly_nut {
            get {
                object obj = ResourceManager.GetObject("earthly_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rotten_nut {
            get {
                object obj = ResourceManager.GetObject("rotten_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap jerky {
            get {
                object obj = ResourceManager.GetObject("jerky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tasty_meat {
            get {
                object obj = ResourceManager.GetObject("tasty_meat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rotten_meat {
            get {
                object obj = ResourceManager.GetObject("rotten_meat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate {
            get {
                object obj = ResourceManager.GetObject("chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap deluxe_chocolate {
            get {
                object obj = ResourceManager.GetObject("deluxe_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap melted_chocolate {
            get {
                object obj = ResourceManager.GetObject("melted_chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate_covered {
            get {
                object obj = ResourceManager.GetObject("chocolate_covered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garigari_soda {
            get {
                object obj = ResourceManager.GetObject("garigari_soda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap garigari_cola {
            get {
                object obj = ResourceManager.GetObject("garigari_cola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap magical_potion {
            get {
                object obj = ResourceManager.GetObject("magical_potion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap solar_nut {
            get {
                object obj = ResourceManager.GetObject("solar_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bad_mushroom {
            get {
                object obj = ResourceManager.GetObject("bad_mushroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap antidote {
            get {
                object obj = ResourceManager.GetObject("antidote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap elixir {
            get {
                object obj = ResourceManager.GetObject("elixir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap drop_of_sun {
            get {
                object obj = ResourceManager.GetObject("drop_of_sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bearnut {
            get {
                object obj = ResourceManager.GetObject("bearnut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap speed_nut {
            get {
                object obj = ResourceManager.GetObject("speed_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap banana {
            get {
                object obj = ResourceManager.GetObject("banana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chocolate_banana {
            get {
                object obj = ResourceManager.GetObject("chocolate_banana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tiptoe_nut {
            get {
                object obj = ResourceManager.GetObject("tiptoe_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap redshroom {
            get {
                object obj = ResourceManager.GetObject("redshroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap blueshroom {
            get {
                object obj = ResourceManager.GetObject("blueshroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap see_all_nut {
            get {
                object obj = ResourceManager.GetObject("see_all_nut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap warp_leaf {
            get {
                object obj = ResourceManager.GetObject("warp_leaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap mr_rainnot {
            get {
                object obj = ResourceManager.GetObject("mr_rainnot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tonniar_rm {
            get {
                object obj = ResourceManager.GetObject("tonniar_rm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sunny_clog {
            get {
                object obj = ResourceManager.GetObject("sunny_clog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap loser_stick {
            get {
                object obj = ResourceManager.GetObject("loser_stick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap winner_stick {
            get {
                object obj = ResourceManager.GetObject("winner_stick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap red_card {
            get {
                object obj = ResourceManager.GetObject("red_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap green_card {
            get {
                object obj = ResourceManager.GetObject("green_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap dark_card {
            get {
                object obj = ResourceManager.GetObject("dark_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sword_license {
            get {
                object obj = ResourceManager.GetObject("sword_license", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap pet {
            get {
                object obj = ResourceManager.GetObject("pet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap vector_coffin {
            get {
                object obj = ResourceManager.GetObject("vector_coffin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap circle_key {
            get {
                object obj = ResourceManager.GetObject("circle_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap triangle_key {
            get {
                object obj = ResourceManager.GetObject("triangle_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap square_key {
            get {
                object obj = ResourceManager.GetObject("square_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cross_key {
            get {
                object obj = ResourceManager.GetObject("cross_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap pile_parts {
            get {
                object obj = ResourceManager.GetObject("pile_parts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fate_goddess_statue {
            get {
                object obj = ResourceManager.GetObject("fate_goddess_statue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap existence_goddess_statue {
            get {
                object obj = ResourceManager.GetObject("existence_goddess_statue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap necessity_goddess_statue {
            get {
                object obj = ResourceManager.GetObject("necessity_goddess_statue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap circlet {
            get {
                object obj = ResourceManager.GetObject("circlet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap cool_bandana {
            get {
                object obj = ResourceManager.GetObject("cool_bandana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap burning_headband {
            get {
                object obj = ResourceManager.GetObject("burning_headband", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earth_amulet {
            get {
                object obj = ResourceManager.GetObject("earth_amulet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap proof_of_shinobi {
            get {
                object obj = ResourceManager.GetObject("proof_of_shinobi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap alfar_tiara {
            get {
                object obj = ResourceManager.GetObject("alfar_tiara", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap x_ray_glasses {
            get {
                object obj = ResourceManager.GetObject("x_ray_glasses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap golden_mask {
            get {
                object obj = ResourceManager.GetObject("golden_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap faded_hat {
            get {
                object obj = ResourceManager.GetObject("faded_hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wolf_fang {
            get {
                object obj = ResourceManager.GetObject("wolf_fang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap colonel_helm {
            get {
                object obj = ResourceManager.GetObject("colonel_helm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap leather_armor {
            get {
                object obj = ResourceManager.GetObject("leather_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap chain_mail {
            get {
                object obj = ResourceManager.GetObject("chain_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap plate_mail {
            get {
                object obj = ResourceManager.GetObject("plate_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap fire_dragon_armor {
            get {
                object obj = ResourceManager.GetObject("fire_dragon_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap ice_dragon_armor {
            get {
                object obj = ResourceManager.GetObject("ice_dragon_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap wind_dragon_armor {
            get {
                object obj = ResourceManager.GetObject("wind_dragon_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap earth_dragon_armor {
            get {
                object obj = ResourceManager.GetObject("earth_dragon_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap raincoat {
            get {
                object obj = ResourceManager.GetObject("raincoat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rune_armor {
            get {
                object obj = ResourceManager.GetObject("rune_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap spike_mail {
            get {
                object obj = ResourceManager.GetObject("spike_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap novice_mail {
            get {
                object obj = ResourceManager.GetObject("novice_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap white_armor {
            get {
                object obj = ResourceManager.GetObject("white_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap black_armor {
            get {
                object obj = ResourceManager.GetObject("black_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap worn_out_coat {
            get {
                object obj = ResourceManager.GetObject("worn_out_coat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bat_wing {
            get {
                object obj = ResourceManager.GetObject("bat_wing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap forte_mantle {
            get {
                object obj = ResourceManager.GetObject("forte_mantle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap power_wrist {
            get {
                object obj = ResourceManager.GetObject("power_wrist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap bracelet {
            get {
                object obj = ResourceManager.GetObject("bracelet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap crest_of_clubs {
            get {
                object obj = ResourceManager.GetObject("crest_of_clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap crest_of_diamonds {
            get {
                object obj = ResourceManager.GetObject("crest_of_diamonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap buckler {
            get {
                object obj = ResourceManager.GetObject("buckler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rune_gauntlet {
            get {
                object obj = ResourceManager.GetObject("rune_gauntlet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap white_gauntlet {
            get {
                object obj = ResourceManager.GetObject("white_gauntlet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap black_gauntlet {
            get {
                object obj = ResourceManager.GetObject("black_gauntlet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sweaty_gloves {
            get {
                object obj = ResourceManager.GetObject("sweaty_gloves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap undead_fingernail {
            get {
                object obj = ResourceManager.GetObject("undead_fingernail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap tomahawk_armor {
            get {
                object obj = ResourceManager.GetObject("tomahawk_armor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap iron_clogs {
            get {
                object obj = ResourceManager.GetObject("iron_clogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap funny_shoes {
            get {
                object obj = ResourceManager.GetObject("funny_shoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap power_ankle {
            get {
                object obj = ResourceManager.GetObject("power_ankle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap traveler_s_shoes {
            get {
                object obj = ResourceManager.GetObject("traveler_s_shoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap sabaton {
            get {
                object obj = ResourceManager.GetObject("sabaton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap winged_boots {
            get {
                object obj = ResourceManager.GetObject("winged_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap adventurer_s_boots {
            get {
                object obj = ResourceManager.GetObject("adventurer_s_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap worn_out_boots {
            get {
                object obj = ResourceManager.GetObject("worn_out_boots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap rat_tail {
            get {
                object obj = ResourceManager.GetObject("rat_tail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>Looks up a localized resource of type System.Drawing.Bitmap.</summary>
        internal static System.Drawing.Bitmap blues_leg {
            get {
                object obj = ResourceManager.GetObject("blues_leg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
